### ISSUE TITLE
Game starts at 9:58 when it should start at 0:00 I think...

### ISSUE THREAD

**Issue by leungandrew** [cannawen/dota2timer#39]
Repro steps:
Start app.

Expected:
Timer starts at 0:00

Actual:
Timer starts at something like 9:58

**Comment by cannawen** [comment]
There was a bug in the latest release. This is fixed in https://github.com/cannawen/dota2timer/commit/49ac1dde3217bb213101577c40f67f26c150fbd7 with [test](https://github.com/cannawen/dota2timer/blob/master/app/src/test/java/com/cannawen/dota2timer/game/DotaGameTest.java#L43)

New build should be up in ~10 minutes
